---
title: "GIS Project"
date: "December 31,  2024"
date-modified: "last-modified"
format: html
execute: 
  freeze: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Overview

The purpose of the GIS project is to provide students with a first hand experience on building a GIS-Enabled Urban Planning Support System by integrating open government data and other open source data sets. You will also learn how to collect, process and analyse spatially related issues using real world data. Students are encouraged to focus on research topics that are relevant to their field of study.

The project is to be done in a team. You are required to form a project team of **2-3 members** by the second week of the academic term. Each project team must start thinking about their project ideas from week 8 onwards. You are expected to discuss your project topic and scope of work with the instructor between week 8-9 of the academic term. A project website must be prepared and will be linked to this page by the end of week 10.

## Topic

TBC

## The Data

TBC

## Scope of Work

The project will comprise of, but not limited to the followings steps:

-   Selection of project focus and conducting literature review.
-   Preparing proposal and project website.
-   Data collection, extraction, integration, transformation and wrangling.
-   Designing and building GIS model and database.
-   Performing GIS analysis.
-   Preparing poster and project webpage.

## Project Milestone

-   Formulation of project team: by week 2 before lesson
-   Assemble GIS data: from week 7 onwards
-   Create project website : by week 8
-   Submission of project poster: **9th April 2025, 11:59PM (mid-night)**.
-   Townhall presentation: **14th April 2025 (Monday), at 12:00-2:00pm**. Venue: LKSLIB Basement concourse. Students are required to be at the venue latest by 11:30am to setup your project poster.
-   Submission of project artifacts and update project webpage: **20th April 2025 at 11.59pm (mid-night)**

## Grading

The GIS project will account for 35% of your final grade in the course. The distribution of marks for each stage of the project are as follows:

-   Townhall presentation (peer evaluation) 15%
-   Project poster 15%
-   Project website and report 30%
-   Minutes of Meeting 15%
-   Project artifact 25%

The course instructor will consider strongly the novelty of the idea (If it has never been done before, you will get lots of credit!), how it addresses the problem at hand, the methodology you employ in doing the research, and your technical skill in implementing the idea.

In small group projects, each person will be graded individually. A good group project is a system consisting of a collection of well-defined subsystems. Each subsystem should be the responsibility of one person and be clearly identified as their project. A good criteria for whether you should work in a group is whether the system as a whole is greater than the sum of its parts!

## Townhall Poster Presentation

A townhall presentation will be held on **14th April 2025 (Monday) between 11.30am - 2.30pm**. The venue will be at LKSLIB Basement concourse.

## Deliverables

### Minutes of Meeting

To formulate the project proposal, you are required to have at least one round of brain-storming session and take down minutes of the discussion, disagreements, and consensus made within the team in the form of **Minutes of Meeting**. At least three differences should be included and a clear documentation on how the final decisions were reached must be provided. The Minutes of Meeting should also record the division of labour and the considerations involved in the decision made.

The following links provided useful guides on how to prepare the minutes of a meeting:

1.  [How to Write Meeting Minutes: Examples + Best Practices](https://fellow.app/blog/meetings/meeting-minutes-example-and-best-practices/)

2.  [How To Write Effective Meeting Minutes withTemplates and Samples](https://www.wildapricot.com/blog/how-to-write-meeting-minutes)

### Project Website

#### Project Github

At the beginning of the project, project teams are required to create a project Github. The project Github should include all the materials used to develop the project and the written materials such as proposal, poster and project report. It must be used to maintain a complete project versioning including the application and project documents. The Github link must be included in the project webpage. By the end of the project, the project team must pack the final version of the Github repository and upload onto eLearn for final submission. The Github link also must be provided on eLearn.

#### Project Website

Each project team are required to create the project website by using [Quarto](https://quarto.org/docs/tools/rstudio.html). It will be disseminated by using [Netfity](https://www.netlify.com/) web server.

-   The title of your project,
-   A short description of not more than 350 words summarising the motivation, objectives, methodology and key findings, and
-   The project proposal.
    -   Motivation of the project
    -   Project objective
    -   Data
    -   Scope of work
    -   Project schedule including a Gantt chart
-   Methodology
    -   a detail documentation of the methods used.
-   Results and Discussion
-   Lesson learned

Please refer to the two parts videos I prepared and shared on eLearn to how to create and edit project website using Quatro and how to publish the project website on Netlify service.

### Poster

The poster should provide an overview of your project. It should include, but not limited to the following information:

-   Issues and problems - A clear statement of the issues or/and problems that your project addresses.
-   Motivation - An explanation of why the issues and/or problems are interesting and what make them difficult to solve.
-   Approach - A description of the GIS analysis and other urban analysis techniques you used to solve the problem.
-   Results - Screenshots and a working demo of the system you built.
-   Future Work - An explanation of how the work could be extended.

The dimensions for the poster must conform to the International Standards Organization (ISO) poster size format (A1).

-   Size = ISO A1 (594 × 841mm or 23.39 × 33.11inci)
-   Resolution = 300dpi or above
-   File format = jpeg

Please ensure that the poster is in high resolution.

The poster will be considered as a final deliverable. So don't forget to apply good visual design principles to both your poster and project report.

Note: The course instructor will be responsible for printing your poster. You are required to upload your posters to the project webpage of your project one week and your project Dropbox before the poster presentation.

Below are sample posters for your reference:

-   [Hut of North](https://wiki.smu.edu.sg/1920t1smt201/G1-Group12_Poster)
-   [What's Best for Jurong West](https://wiki.smu.edu.sg/1920t1smt201/G2-Group07_Poster)

### Final Deliverable

The final deliverable will include:

-   Fully updated project webpage
-   Project Poster on project webpage
-   Project Report on project webpage
-   Project artifact, the complete GIS project folder including but not limited to raw data, process data, QGIS project file, and output maps.

#### Project Report

The project report should focus on but not limited to the followings:

-   A detailed discussion of the GIS analysis process and functions used.
-   A comprehensive discussion of the analysis results.
-   A collection of analytical maps (can be statics or interactive web maps)

#### Submission instruction

The project artifact is due (submitted to LMS Dropbox) by the end of the day on **20th April 2025 at 11.59pm (mid-night)**.

## Sample Projects

Note that the following examples are for references purposes. You are urged to use your own creativity and innovation to design the application.

-   [AY2019-2020 Term 1 Project](https://wiki.smu.edu.sg/1920t1smt201/Project_Groups)
    -   [G1-Group3 Innogol](https://wiki.smu.edu.sg/1920t1smt201/G1-Group03)
    -   [G2-Group15 Nothing is 台南](https://wiki.smu.edu.sg/1920t1smt201/G2-Group15_About)
-   AY2020-2021 Term 1
    -   [Group 2](https://smt201-g1.netlify.app/)
    -   [Group 4](https://smt201group4project.netlify.app/)
-   AY2022-2023 Term 1
    -   [Singapore: A "Garden City"?](https://smt201team06.netlify.app/)
    -   [Mass Relevant Transport](https://gisprojectg1t10.netlify.app/)
    -   [Urban Sensing With Satellites - Jurong Lake District](https://urbansensingjld.netlify.app/)
    -   [Land Cover Change Detection of Punggol](https://smt201-group9.netlify.app/)
    -   [The Cost of Coast?](https://smt201g2team10.netlify.app/)
    -   [Al Norte](https://gisproject-g2t11.netlify.app/)
-   AY2023-24 Term 1
    -   [Group 1: Rise of Derna Guardiens](https://geomusketeers.netlify.app/)
    -   [Group 2: 2023 LIBYA FLOOD](https://smt201-g2-2023.netlify.app/)
    -   [Group 3: Saving Derna](https://smt201-gist3.netlify.app/)
    -   [Group 4: FloodSafe: Derna, Libya](https://smt201groupproject.netlify.app/)
    -   [Group 5: Derna EvacuConnect](https://smt201-grp5-ay2023-24t1.netlify.app/)
    -   [Group 6: Accessibility Analysis and Mapping of Emergency Evacuation Centres and Medical Services](https://smt201ay23-24-group6.netlify.app/)
    -   [Group 7: Untitled](https://gisproject-group7.netlify.app/)
    -   [Group 8: Untitled](https://long-phung-urban-pte-ltd.netlify.app/)
    -   [Group 9: Land Cover Change Analysis in Libya 2023](https://smt201-group9-libya-flood-mapping.netlify.app/)
    -   [Group 10: FloodScape](https://smt201-ay2023-24t1-team10.netlify.app/)
    -   [Group 11: Derna in Distress](https://smt201-group11.netlify.app/)

## Getting Started with Quarto

-   Downloading and installing the latest version of R
    -   For Windows users, use this [link](https://cran.r-project.org/bin/windows/base/)

    -   For Mac OS users, use this [link](https://cran.r-project.org/bin/macosx/)
-   Downloading and installing the latest version of RStudio (if you have yet to do so!)
    -   Visit this [link](https://www.rstudio.com/products/rstudio/download/#download).
-   Downloading and installing Quarto (if you have yet to do so!)
    -   Visit this [link](https://quarto.org/docs/get-started/) to download Quarto installer.
-   Installing git
    -   Download git at this [link](https://git-scm.com/downloads) and install in your computer.
-   Register with github
    -   visit this [link](https://github.com/) and create a github account.
-   Connecting git with RStudio
    -   Visit this [link](https://r4dsa.netlify.app/posts/2021-05-22-git-in-rstudio/) for instruction.
-   Signing up at Netlify
    -   visit this [link](https://www.netlify.com/) and signing up with Netlify.
-   Installing [**usethis**](https://usethis.r-lib.org/) R package with RStudio.
-   Solving git(GitHub) token issue (optional)
    -   Refer to this [article](https://r4dsa.netlify.app/posts/2021-05-23-git-token/) if encountered git and gitHub credential issue when you need to connect a local repo with GitHub.

### Useful link to learn more about Quarto

-   [Exploring RStudio's Visual Markdown Editor](https://www.rstudio.com/blog/exploring-rstudio-visual-markdown-editor/)
-   [HTML Theming](https://quarto.org/docs/output-formats/html-themes.html)
-   [Markdown Basics](https://quarto.org/docs/authoring/markdown-basics.html)
-   [Quarto Websites](https://quarto.org/docs/websites/)

## Peer Learning



## Reference

### Non-academic Publication

[Derna: The Libyan city known for rebellion --- and neglect](https://www.dw.com/en/derna-the-libyan-city-known-for-rebellion-and-neglect/a-66822261)

[Derna dam collapses](https://en.wikipedia.org/wiki/Derna_dam_collapses)

[Floods worsened by Dams collapse lead to deaths of thousands in Libya](https://sandrp.in/2023/09/13/floods-worsened-by-dams-collapse-lead-to-deaths-of-thousands-in-libya/)

[Libya flooding: before and after satellite images reveal scale of disaster in Derna](https://www.theguardian.com/world/2023/sep/13/libya-flooding-before-and-after-satellite-images-northeastern-floods-derna)

[Libya flood: Satellite images and aerial photographs show destruction](https://www.bbc.com/news/world-africa-66807956)

[See why Libya's floods were so deadly in maps and videos](https://www.washingtonpost.com/world/2023/09/12/deadly-libya-flooding-cause/)

[Storm Daniel, Libya, September 2023](https://storymaps.arcgis.com/stories/e451e32a054847469b1c1c731a8e5cff)

### Research Publication

[GIS in Urban Disaster Management](https://www.researchgate.net/publication/282287006_GIS_in_urban_disaster_management).

George D. Bathrellos et. al. (2023) [Natural and Technological Hazards in Urban Areas Assessment, Planning and Solutions](https://www.mdpi.com/books/book/6614)

Abdalla, Rifaat [Evaluation of spatial analysis application for urban emergency management](https://springerplus.springeropen.com/articles/10.1186/s40064-016-3723-y), *SpringerPlus*, 2016, Vol.5 (1), p.2081-2081.

Elkhrachy, Ismail [Assessment and Management Flash Flood in Najran Wady Using GIS and Remote Sensing](https://search.library.smu.edu.sg/discovery/fulldisplay?docid=cdi_proquest_journals_2007703386&context=PC&vid=65SMU_INST:SMU_NUI&lang=en&search_scope=Everything&adaptor=Primo%20Central&tab=Everything&query=any%2Ccontains%2CGIS%20for%20urban%20flood%20emergency%20management&offset=0), *Journal of the Indian Society of Remote Sensing*, 2018, Vol.46 (2), p.297-308.

Albano, R ; Sole, A ; Adamowski, J ; Mancusi, L () [A GIS-based model to estimate flood consequences and the degree of accessibility and operability of strategic emergency response structures in urban areas](https://search.library.smu.edu.sg/view/action/uresolver.do?operation=resolveService&package_service_id=5332606640002601&institutionId=2601&customerId=2600&VE=true), *Natural Hazards and Earth System Sciences*, Vol.14 (11), p.2847-2865.

Karymbalis, Efthimios et. al. (2021) [Integration of GIS-Based Multicriteria Decision Analysis and Analytic Hierarchy Process for Flood-Hazard Assessment in the Megalo Rema River Catchment(EastAttica,Greece)](https://www.mdpi.com/2071-1050/13/18/10232), *Sustainability*, Vol.13 (18), p.10232

Shi, Hongbin et. al. (2023) [A Study on the Accessibility of the Emergency Medical Services for Urban Kindergartens and Nursing Homes Based on Urban Pluvial Flooding Scenarios](https://www.mdpi.com/2071-1050/15/13/10443), *Sustainability*, Vol.15 (13), p.10443

Si, Yunrui ; Li, Junli ; Si, Youbin (2023) [Urban Flood Loss Estimation and Evacuation Design Based on a 500-Year Extreme Flood Event in Syracuse City](https://www.mdpi.com/2073-4441/15/1/3), *Water*, Vol.15 (1), p.3

Qianqian Zhou et. al. (2021) [A GIS-Based Hydrological Modeling Approach for Rapid Urban Flood Hazard Assessment](https://www.mdpi.com/2073-4441/13/11/1483), *Water* 2021, 13(11), 1483.

Wei Zhu et. al. (2022) \[Urban Flood-Related Remote Sensing: Research Trends, Gaps and Opportunities\] (https://www.mdpi.com/2072-4292/14/21/5505), *Remote Sensing*. 14(21), 5505.

Marco Chini et. al. (2019) [Sentinel-1 In SAR Coherence to Detect Flood water in Urban Areas: Houston and Hurricane Harvey as A Test Case](https://www.mdpi.com/2072-4292/11/2/107). *Remote sensing*, Vol.11 (2), p.107.

Zhixia Wu et. al. (2023) [Urban Flood Loss Assessment and Index Insurance Compensation Estimation by Integrating Remote Sensing and Rainfall Multi-Source Data: A Case Study of the 2021 Henan Rainstorm](https://www.mdpi.com/2071-1050/15/15/11639). *Sustainability*, 15(15), 11639.

Oliveira, E.R.; Disperati, L.; Alves, F.L. (2023) [MINDED-FBA: An Automatic Remote Sensing Tool for the Estimation of Flooded and Burned Areas](https://www.mdpi.com/2072-4292/15/3/724). *Remote Sensing*, 28 pages.

Manuel A. Aguilar et. al. (2016) ["Classification of urban areas from GeoEye-1 imagery through texture features based on Histograms of Equivalent Patterns"](https://www.tandfonline.com/doi/abs/10.5721/EuJRS20164906) *European Journal of Remote Sensing*, Vol. 49, pp. 93-120.
