---
title: "Take-home Exercise 2: Urban Applications of Raster-based GIS Analysis"
date: "February 18, 2025"
date-modified: "last-modified"
format: html
---

::: callout-note
This handout provides the context, task, expectations and grading criteria of Take-home Exercise 2. Students must review and understand them before getting started with the take-home exercise.
:::

## Setting the Scene

Urban planning and business development are essential components in building vibrant, thriving cities. Urban managers carry the crucial responsibility of making decisions that shape the economic future of their communities.

These decisions extend far beyond merely deciding where businesses should be located. They require a careful analysis of potential economic impacts, such as job creation, tax revenue, environmental sustainability, and long-term community benefits. In this regard, data plays a pivotal role in helping city managers make informed decisions that maximize positive outcomes for local economies.

Geospatial data, particularly the location of businesses, enables urban managers to move beyond guesswork, relying on empirical evidence for decision-making. By analyzing the distribution of businesses from previous planning periods, urban planners can identify gaps in land-use planning, such as areas where certain types of businesses are underrepresented. Recognising these gaps empowers planners to revise, refine, and recommend more effective land-use strategies for the upcoming planning period.

## Task

In this take-home exercise, you are required to use QGIS to complete the following tasks:

-   select one of the business group from SSIC 2020,
    -   C MANUFACTURING
    -   G WHOLESALE AND RETAIL TRADE: 46 WHOLESALE TRADE
    -   G WHOLESALE AND RETAIL TRADE: 47 RETAIL TRADE
-   extract and geocode the selected businesss,
-   convert the data from aspatial to geospatial,
-   using appropriate raster-based GIS analyse methods analyse the spatial patterns of the selected business during the URA Plan 2019 period.
-   with reference to the analysis results, provide landuse planning recommendation for URA Master Plan 2025 consideration.

## Take-home Exercise Deliverable

### GIS data repository

The GIS repository includes but not limited to geospatial data compiled and derived, QGIS project file and data dictionary. It must be in a single zipped file (i.e. .zip). The geospatial data must be stored in a GeoPackage database format. The data dictionary can be in either MS Word document or edited into the GIS data. The project deliverable must be uploaded onto eLearn. If the file size beyond the permitted space of eLearn, you can use SMU OneDrive to share the repository with me.

::: callout-note
You can save the raster data in geotiff format. Please do keep these data in a single folder called geotiff.
:::

### Take-home Exercise Report

You are required to edit your take-home exercise report in MS Word format. The take-home exercise report, beside others, should include all the thematic maps prepared and their respective discussion.

More importantly, the report must provide a **reproducible** step-by-step guide on the following process:

-   data compilation, extraction and integration,
-   data cleaning, preparation and wrangling,
-   GIS analysis (including tabular and graphical analysis), and
-   GIS maps design.

::: callout-note
**Reproducible** means that readers are able to perform the same analysis and obtain similar results by using the same data sets and by following the step-by-step guide.
:::

The title of the report should be in the form of *SMT201_AY2024-25T2_Take-home_Exercise2*.

::: callout-warning
This is an individual exercise. You are required to work on the take home exercise and prepare submission individually.
:::

## Grading

-   Quality of the GIS data model built (including metadata) (20 marks),
-   Appropriateness of the GIS methods used (20 marks),
-   Quality of GIS maps prepared (20 marks),
-   Reproducibility of the GIS processes (20 marks)
-   Ability to provide correct interpretation of the analysis results and to recommend appropriate alternatives (20 marks).

## Submission Date

The take-home exercise deliverable must be uploaded on eLearn by the submission deadline stated below.

Due Date: **9th March 2025, 11:59pm (Sunday midnight)**.

## References

- "[Mapping Urban Spatial Structure Based on POI
(Point of Interest) Data: A Case Study of the Central
City of Lanzhou, China](https://www.mdpi.com/2220-9964/9/2/92)".  Please pay special attention to *sub-sections 4.2.2. The Kernel Density Estimation (KDE)* and *5.3.1. The Kernel Density Analysis of Industrial Elements*.







