---
title: "Take-home Exercise 1: Urban Applications of Vector-based GIS Analysis"
date: "January 5, 2025"
date-modified: "last-modified"
format: html
execute: 
  freeze: true
---

## Overview

This handout provides the context, task, expectations and grading criteria of Take-home Exercise 1. Students must review and understand them before getting started with the take-home exercise.

## Setting the Scene

Every fives years, Urban Redevelopment Authority of Singapore will publish the new [Land-Use Master Plan (MP)](https://www.ura.gov.sg/Corporate/Planning/Master-Plan). It is the statutory land use plan which guides Singapore’s development in the medium term over the next 10 to 15 years. The latest version was published in [27th Nov 2019](https://www.ura.gov.sg/Corporate/Planning/Master-Plan/Master-Plan-2019) and the digital version is available at data.gov.sg. Currently, URA are in the process of preparing Master Plan 2025 and [inviting public participation](https://www.ura.gov.sg/Corporate/Planning/Master-Plan/Draft-Master-Plan-2025).

As a socially conscious GIS analyst, you have decided to conduct a study to reveal the distribution of new businesses between the Master Plan 2019 period (i.e. 2020-2024). The study aims to provide policy makers as well as general public analytical-centric information for supporting inclusive and participatory planning process.

## Task

In this take-home exercise, we are interested to prepare a report of survey focusing on the growth and geographic distribution of urban economy such as manufacturing industry, wholesaling, retailing and professional services during URA Master Plan 2019. We are especially interest to understand the utilisation level of the gazetted commecial landuse of Master Plan 2019 by newly registered businesses between the planning period (2020-2024).

The specific tasks of this hands-on exercise are as follow:

-   Determine Business land uses allocated by Master Plan 2019 (excluding those already allocated in Master Plan 2014).
-   Select a business type by referring to 2-digit or 3-digit [Singapore Standard Industrial Classification (SSIS) 2020](https://www.singstat.gov.sg/standards/standards-and-classifications/ssic)
-   Prepare a series of thematic maps by using appropriate mapping techniques showing the spatio-temporal patterns of the selected businesses at yearly interval (i.e. 2020, 2021, 2022, 2023 & 2024). Appropriate data visualisation and/or table(s) can be used to complement the maps.
-   For each geovisualisation prepared, write a short report of not more than 150 words describing the spatio-temporal patterns revealed by the geovisualisation.\
-   With reference to the analysis results above, discuss how these findings can be used to support urban land use planning and management. (Not more than 500 words)

## Data

For the purpose of this study, the following data should be used:

-   Master Plan 2014 Land Use,
-   Master Plan 2019 Land Use, and
-   ACRA Information on Corporate Entities

Other useful GIS data sets can be added if they are necessary.

## Take-home Exercise Deliverable

### GIS data repository

The GIS repository includes but not limited to geospatial data compiled and derived, QGIS project file and data dictionary. It must be in a single zipped file (i.e. .zip). The geospatial data must be stored in a GeoPackage database format. The data dictionary can be in either MS Word document or edited into the GIS data.The project deliverable must be uploaded onto eLearn.

### Take-home Exercise Report

You are required to edit your take-home exercise report in MS Word format. The take-home exercise report, beside others, should include all the thematic maps prepared and their respective discussion.

More importantly, the report must provide a **reproducible** step-by-step guide on the following process:

-   data compilation, extraction and integration,
-   data cleaning, preparation and wrangling,
-   GIS analysis (including tabular and graphical analysis), and
-   GIS maps design.

> Note: **Reproducible** means that readers are able to perform the same analysis and obtain similar results by using the same data sets and by following the step-by-step guide.

The title of the report should be in the form of *SMT201_AY2024-25T1_Take-home_Exercise1*.

> Note: This is an individual exercise. You are required to work on the take home exercise and prepare submission individually.

## Grading

-   Quality of the GIS data model built (including metadata) (20 marks),
-   Appropriateness of the GIS methods used (20 marks),
-   Quality of GIS maps prepared (20 marks),
-   Reproducibility of the GIS processes (20 marks)
-   Ability to provide correct interpretation of the analysis results and to recommend appropriate alternatives (20 marks).

## Submission Date

The take-home exercise deliverable must be uploaded on eLearn by the submission deadline stated below.

Due Date: **16th February 2025, 11:59pm (midnight)**.
