---
title: "Lesson 11: Urban Land Cover Change Detection with Remotely Sensed Data"
date: "December 31, 2024"
date-modified: "last-modified"
format: html
execute: 
  freeze: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Overview

In this lesson, you will learn how to perform land cover change detection by using remotely sensed data and digital image analysis methods.

## Content

-   Land Cover Change Detection in the Context of Urban Planning
-   Urban Land Cover Change Detection Techniques
    -   Pre-classification 
    -   Post-classification
    -   Change Vector Analysis
    -   Time Series Analysis


## Lesson Slides and Hands-on Notes

-   Lesson slides in [html](../lesson/Lesson11/Lesson11.html) format.

-   Hands-on Exercise 11 in [html](https://qgis4rdpa.netlify.app/hands-on_00) format.

## References

### Articles

-   Sandipta Das . Dasharatha P Angadi (2022) ["*Land use land cover change detection and monitoring of urban growth using remote sensing and GIS techniques: a micro-level study*"](https://link-springer-com.libproxy.smu.edu.sg/content/pdf/10.1007/s10708-020-10359-1.pdf) **GeoJournal**, Vol. 87, pp. 2101--2123.

-   Jane Ferah Gondwe, Sun Lin, Rodger Millar Munthali, ["*Analysis of Land Use and Land Cover Changes in Urban Areas Using Remote Sensing: Case of Blantyre City*"](https://www.hindawi.com/journals/ddns/2021/8011565/), **Discrete Dynamics in Nature and Society**, vol. 2021, Article ID 8011565, 17 pages, 2021. https://doi.org/10.1155/2021/8011565

-   Geymen, Abdurrahman ; Baz, Ibrahim (2007) [*Monitoring urban growth and detecting* land-cover changes on the Istanbul metropolitan area](https://link-springer-com.libproxy.smu.edu.sg/article/10.1007/s10661-007-9699-x), **Environmental Monitoring and Assessment**, Vol.136 (1-3), p.449-459.

-   Yin, Jie et. al. (2010) [*Monitoring urban expansion and land use/land cover changes of Shanghai metropolitan area during the transitional economy (1979--2009) in China*](https://link-springer-com.libproxy.smu.edu.sg/article/10.1007/s10661-010-1660-8), **Environmental Monitoring and Assessment**, Vol.177 (1-4), p.609-621.

-   Praveen Kumar Mallupattu\* and Jayarama Reddy Sreenivasula Reddy (2013) [*Analysis of Land Use/Land Cover Changes Using Remote Sensing Data and GIS at an Urban Area, Tirupati, India*](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3679719/), **The Scientific World Journal** (online)

### QGIS Methods

-   [Landcover change detection using QGIS. Land use landcover change detection](https://www.youtube.com/watch?v=4XKgVwrztXY)

-   [Step-by-Step: Land Cover Change Detection through Supervised Classification](https://www.un-spider.org/advisory-support/recommended-practices/recommended-practice-land-cover-change/step-by-step).

-   [Calculating Land surface temperature using Landsat 8 Imagery \|\| QGIS Tutorial](https://www.youtube.com/watch?v=OGX8oVgS-QE)

### QGIS Plugin

-   [Semi-Automatic Classification Plugin (SCP) for QGIS](https://fromgistors.blogspot.com/p/semi-automatic-classification-plugin.html)
-   [Orfeo toolbox Plugin for QGIS](https://www.orfeo-toolbox.org/CookBook/index.html)
-   [OTB Plugin installation](http://wiki.awf.forst.uni-goettingen.de/wiki/index.php/OTB_Plugin_installation)
-   [Object-based Image classification in QGIS](https://www.youtube.com/watch?v=fX2UpOwoYLk). This video tutorial demonstrates the use of OTB to perform Object-based Image classification (OBIA).
-   [GEOBIA](https://github.com/salomoneinstein/QuickStepGeobia)
-   [GEOBIA - Geographic Object-Based Image Analysis](https://www.youtube.com/watch?v=oW7l4vUlr3A). This video tutorial tutorial demonstrates the use GEOBIA QGIS plugin to perform Geographic Object-Based Image Analysis (GEOBIA).
-   [dzetsaka: Classification tool](https://github.com/nkarasiak/dzetsaka) supports Random Forest, KNN and SVM for supervised classification of multi-spectral satellite data.
-   [Neural Network MLPClassifier](https://mlp-image-classifier.readthedocs.io/en/latest/index.html) provides a supervised classification method for multi-band passive optical remote sensing data based on the Neural Network MLPClassifier by scikit-learn.
-   [GEOSYS Plugin](https://github.com/GEOSYS/qgis-plugin)
-   [PCA4CD - PCA for change detection](https://github.com/SMByC/PCA4CD)
-   [buildseg: QGIS plugin for building extraction](https://github.com/deepbands/buildseg)
-   [Terminus](https://github.com/ikotarid/Terminus)
-   [Tree Density Calculator](https://treedensitycalculator.readthedocs.io/en/latest/#)
-   [RS&GIS](https://github.com/PrathamGitHub/NITK_RS-GIS_17)
